#Custom route for sitemap.xml
sitemap:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::index

gregwar_captcha_routing:
  resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"